# services:
#   todo-application:
#     image: faizan2203/todo-application:latest
#     container_name: todo-application
#     # command: bat -c "sleep 20 && java -jar app.jar"
#     ports:
#       - "8082:8081"
#     depends_on:
#       - mysql-db
#     networks:
#       - todo-network
#   mysql-db:
#     image: mysql:8
#     container_name: mysql-db
#     environment:
#       - MYSQL_ROOT_PASSWORD=Root@123
#       - MYSQL_DATABASE=tododb
#       # - MYSQL_USER=root
#       # - MYSQL_PASSWORD=Nuvelabs123$
#     ports:
#       - "3307:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql
#     networks:
#       - todo-network
# volumes:
#   mysql-data:
# networks:
#   todo-network:
#     driver: bridge
version: "3.8"

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=Root@123
      - MYSQL_DATABASE=tododb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pRoot@123"]
      interval: 10s
      timeout: 5s
      retries: 5

  todo-application:
    image: faizan2203/todo-application:latest
    container_name: todo-application
    ports:
      - "8082:8081"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - todo-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/tododb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Root@123

volumes:
  mysql-data:

networks:
  todo-network:
    driver: bridge
